services:
        Wikipedia:
            classname: services.wikipediaservice.WikipediaService
        Weather:
            classname: services.openweathermap.WeatherService
            url: http://api.openweathermap.org/data/2.5/weather
            api_key: <YOUR_API_KEY>
        GPT2:
            classname: services.gpt2.GPT2Service
            url: 'https://api-inference.huggingface.co/models/gpt2'

        SentimentAnalysis:
            classname: services.sentimentanalysis.SentimentAnalysisService
            url: /home/rohola/codes/service_oriented_py/model/pretrain_distilbert_full_sentiment

host: 127.0.0.1
port: 3000