services:

        # Online Content Services
        Wikipedia:
            classname: services.wikipediaservice.WikipediaService
        # Weather:
        #     classname: services.openweathermap.WeatherService
        #     url: 'http://api.openweathermap.org/data/2.5/weather'
        #     api_key: <YOUR_API_KEY>
        News:
            classname: services.news.BingNewsService
            url: 'https://microsoft-azure-bing-news-search-v1.p.rapidapi.com/'
            headers:
                x-rapidapi-host: '<YOUR_API_HOST>'
                x-rapidapi-key: '<YOUR_API_KEY>'

        # NLP Services
        GPT2:
            classname: services.gpt2.GPT2Service
            url: 'https://api-inference.huggingface.co/models/gpt2'
        SentimentAnalysis:
            classname: services.sentimentanalysis.SentimentAnalysisService
            url: './models/pretrain_distilbert_full_sentiment'
        SemanticSimilarity:
            classname: services.semanticsimilarity.SemanticSimilarityService
            url: './models/pretrain_distilroberta'
                        
            

host: 127.0.0.1
port: 3000